### ISSUE TITLE
Appending an html element 

### ISSUE THREAD

**Issue by cindyytong** [sharshi/W9D5-Classwork#1]
We want to append on the same types of objects.  If we have an html element we want to first convert that to an instance of DOM Node Collection and then append it.  Similar to how the $() jquery methods lets us return a jquery object we can use $l(arg) to wrap it as an instance of DOM Node Collection.  

https://github.com/sharshi/W9D5-Classwork/blob/f5cc3b985b891689c7b4745c1f4b5dbbe0f6cf7a/jQueryLite/src/dom_node_collection.js#L37

**Comment by sharshi** [comment]
If I understand correctly, I will either be passing in a string or a DOMNodeCollection, but never a plain HTMLElement?

**Comment by sharshi** [comment]
or:
```js
if (el instanceof HTMLElement) {
  el = $l(el);
}
...rest of .append method
```
